<a href="https://colab.research.google.com/github/georgeduranh/ML/blob/main/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim 

42


0

In [3]:
vector = np.array([1, 2, 3])
print(vector) 
vector.ndim

[1 2 3]


1

In [4]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [5]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

Agregar o eliminar dimensiones

In [6]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [7]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

In [9]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1




Reto

    Definir un tensor de 5D
    Sumarle una dimensión en cualquier eje
    Borrar las dimensiones que no se usen



In [11]:
tensor =  np.array([1, 2, 3], ndmin = 5)
print(tensor) 
tensor.ndim 

[[[[[1 2 3]]]]]


5

In [13]:
expand = np.expand_dims(tensor, axis = 0)
print(expand)
expand.ndim 

[[[[[[1 2 3]]]]]]


6

In [14]:
vector_2 = np.squeeze(expand)
print(vector_2, vector_2.ndim)

[1 2 3] 1
