<a href="https://colab.research.google.com/github/georgeduranh/ML/blob/main/5_shape_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (3,2))

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[6, 8],
       [5, 1],
       [5, 6]])

In [5]:
arr.reshape(1,6)

array([[6, 8, 5, 1, 5, 6]])

In [6]:
arr.reshape(2,3)

array([[6, 8, 5],
       [1, 5, 6]])

In [7]:
np.reshape(arr, (2,3))

array([[6, 8, 5],
       [1, 5, 6]])

In [8]:
arr

array([[6, 8],
       [5, 1],
       [5, 6]])

In [9]:
np.reshape(arr, (2,3), 'C')

array([[6, 8, 5],
       [1, 5, 6]])

In [10]:
np.reshape(arr, (2,3), 'F')

array([[6, 5, 1],
       [5, 8, 6]])

In [14]:
#Optimizado par el almacenamiento en mi sistema
np.reshape(arr, (2,3), 'A')

array([[6, 8, 5],
       [1, 5, 6]])