<a href="https://colab.research.google.com/github/georgeduranh/ML/blob/main/6_main_nupmy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20, 10)

In [7]:
matriz = arr.reshape(2,5)
matriz

array([[ 1, 16, 19,  8, 11],
       [ 6,  4, 17, 12, 19]])

In [9]:
arr.max()

19

In [10]:
matriz.max()

19

In [11]:
matriz.max(0)

array([ 6, 16, 19, 12, 19])

In [12]:
matriz.max(1)

array([19, 19])

In [13]:
matriz.argmax()

2

In [14]:
matriz.min()

1

In [15]:
matriz.argmin()

0

In [17]:
arr.ptp()

18

In [18]:
arr

array([ 1, 16, 19,  8, 11,  6,  4, 17, 12, 19])

In [20]:
matriz.ptp(0)

array([ 5, 12,  2,  4,  8])

In [25]:
np.percentile(arr, 50)

11.5

In [29]:
arr.sort()
arr

array([ 1,  4,  6,  8, 11, 12, 16, 17, 19, 19])

In [32]:
np.median(arr)

11.5

In [33]:
np.median(matriz, 0)

array([ 6.5, 10. , 11.5, 13.5, 15. ])

In [34]:
np.std(arr)

6.1

In [35]:
np.var(arr)

37.21

In [36]:
np.mean(arr)

11.3

In [39]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [41]:
b = np.array([5,6])
b 

array([5, 6])

In [44]:
np.concatenate((a,b), axis=0)

ValueError: ignored

In [46]:
a.ndim

2

In [47]:
b.ndim

1

In [48]:
b = np.expand_dims(b, 0)

In [49]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.concatenate((a,b), axis=1)

ValueError: ignored

In [51]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])