<a href="https://colab.research.google.com/github/georgeduranh/ML/blob/main/8_condiciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
arr = np.linspace(1,10, 10, dtype=np.int8)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [8]:
index_cond = arr > 5
index_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
arr[index_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
np.where(arr > 1, 0, 10)

array([10,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [12]:
arr[(arr > 5 ) & ( arr <9)]

array([6, 7, 8], dtype=int8)

In [13]:
arr[(arr > 5 )] = 99

In [14]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)