<a href="https://colab.research.google.com/github/georgeduranh/ML/blob/main/7_copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [16]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
sub_arr = arr[0:6]
sub_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
sub_arr[:] = 0
sub_arr

array([0, 0, 0, 0, 0, 0])

In [10]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [11]:
#New space in memory
arr_copy = arr.copy()

In [17]:
sub_arr = arr_copy[0:6]
sub_arr[:] = 10
sub_arr

array([10, 10, 10, 10, 10, 10])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])