<a href="https://colab.research.google.com/github/georgeduranh/ML/blob/main/9_operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
lista = [1,2]
lista

[1, 2]

In [4]:
lista*2

[1, 2, 1, 2]

In [6]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [7]:
##Operaciones
arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
11 / arr 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222])

In [11]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [18]:
np.matmul(matriz , matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [19]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])